apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pushbeam-data
  labels:
    app.kubernetes.io/name: pushbeam-server
    app.kubernetes.io/part-of: pushbeam
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
