apiVersion: v1
kind: Service
metadata:
  name: pushbeam-server
  labels:
    app.kubernetes.io/name: pushbeam-server
    app.kubernetes.io/part-of: pushbeam
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pushbeam-server
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
